// This file will be auto-generated by:
// npx supabase gen types typescript --project-id <your-project-id> > src/types/database.types.ts
//
// For now, using a permissive placeholder so TypeScript compiles.
// Once you run `supabase gen types`, this file will be replaced with
// the real schema types and all queries will be fully type-safe.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Database {
  public: {
    Tables: Record<
      string,
      {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
        Relationships: unknown[];
      }
    >;
    Views: Record<
      string,
      {
        Row: Record<string, unknown>;
        Relationships: unknown[];
      }
    >;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
    CompositeTypes: Record<string, unknown>;
  };
}
